flags:
  unit:
    paths:
      - 'packages/vern-llm/**'
  integration:
    paths:
      - 'packages/vern-llm/**'
  vern-llm-redis-unit:
    paths:
      - 'packages/vern-llm-redis/**'
  vern-llm-redis-integration:
    paths:
      - 'packages/vern-llm-redis/**'
  vern-llm-otel-unit:
    paths:
      - 'packages/vern-llm-otel/**'
  vern-llm-otel-integration:
    paths:
      - 'packages/vern-llm-otel/**'

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        paths:
          - 'packages/vern-llm/**'
      vern-llm-redis:
        target: auto
        threshold: 0.5%
        paths:
          - 'packages/vern-llm-redis/**'
      vern-llm-otel:
        target: auto
        threshold: 0.5%
        paths:
          - 'packages/vern-llm-otel/**'
    patch:
      default:
        target: 80%
        paths:
          - 'packages/vern-llm/**'
      vern-llm-redis:
        target: 80%
        paths:
          - 'packages/vern-llm-redis/**'
      vern-llm-otel:
        target: 80%
        paths:
          - 'packages/vern-llm-otel/**'

ignore:
  - '**/index.ts'
  - 'apps/**'
