import { describe, it, expect } from 'vitest';

import {
  fromCerebras,
  fromDeepInfra,
  fromDeepSeek,
  fromFireworks,
  fromGroq,
  fromHyperbolic,
  fromLMStudio,
  fromMistral,
  fromMoonshot,
  fromNovita,
  fromOllama,
  fromOpenAICompatible,
  fromOpenRouter,
  fromPerplexity,
  fromTogether,
  fromVLLM,
  fromZhipu,
  fromXAI,
  fromNvidiaNIM,
  fromVercelAIGateway,
  fromCloudflareWorkersAI,
  fromGitHubModels,
  fromNebius,
  fromSambaNova,
  fromBaseten,
  fromFeatherless,
  fromFriendli,
  fromSiliconFlow,
  fromParasail,
  fromStepFun,
  fromMiniMax,
  fromLambdaLabs,
  fromSnowflakeCortex,
  fromAnyscale,
  fromLepton,
  fromKlusterAI,
  fromInferenceNet,
  fromInfermatic,
  fromAtlasCloud,
  from01AI,
} from '../../../src/adapters/index.js';

describe('fromOpenAICompatible and its aliases', () => {
  it('returns the same client instance untouched (pure passthrough)', () => {
    const fakeClient = { chat: { completions: { create: async () => ({}) } } };
    expect(fromOpenAICompatible(fakeClient)).toBe(fakeClient);
  });

  it.each([
    ['fromGroq', fromGroq],
    ['fromMistral', fromMistral],
    ['fromDeepSeek', fromDeepSeek],
    ['fromCerebras', fromCerebras],
    ['fromTogether', fromTogether],
    ['fromFireworks', fromFireworks],
    ['fromOllama', fromOllama],
    ['fromOpenRouter', fromOpenRouter],
    ['fromPerplexity', fromPerplexity],
    ['fromDeepInfra', fromDeepInfra],
    ['fromNovita', fromNovita],
    ['fromHyperbolic', fromHyperbolic],
    ['fromMoonshot', fromMoonshot],
    ['fromZhipu', fromZhipu],
    ['fromLMStudio', fromLMStudio],
    ['fromVLLM', fromVLLM],
    ['fromXAI', fromXAI],
    ['fromNvidiaNIM', fromNvidiaNIM],
    ['fromVercelAIGateway', fromVercelAIGateway],
    ['fromCloudflareWorkersAI', fromCloudflareWorkersAI],
    ['fromGitHubModels', fromGitHubModels],
    ['fromNebius', fromNebius],
    ['fromSambaNova', fromSambaNova],
    ['fromBaseten', fromBaseten],
    ['fromFeatherless', fromFeatherless],
    ['fromFriendli', fromFriendli],
    ['fromSiliconFlow', fromSiliconFlow],
    ['fromParasail', fromParasail],
    ['fromStepFun', fromStepFun],
    ['fromMiniMax', fromMiniMax],
    ['fromLambdaLabs', fromLambdaLabs],
    ['fromSnowflakeCortex', fromSnowflakeCortex],
    ['fromAnyscale', fromAnyscale],
    ['fromLepton', fromLepton],
    ['fromKlusterAI', fromKlusterAI],
    ['fromInferenceNet', fromInferenceNet],
    ['fromInfermatic', fromInfermatic],
    ['fromAtlasCloud', fromAtlasCloud],
    ['from01AI', from01AI],
  ])('%s is an alias for fromOpenAICompatible', (_name, fn) => {
    expect(fn).toBe(fromOpenAICompatible);
  });
});
